In [115]:
# Panda hostname/IP and Desk login information of your robot
hostname = '192.168.1.11'
username = 'panda'
password = 'panda1234'

# panda-py is chatty, activate information log level
import logging
logging.basicConfig(level=logging.INFO)

In [116]:
import panda_py

desk = panda_py.Desk(hostname, username, password, platform="fr3")

desk.unlock()
desk.activate_fci()

INFO:desk:Login succesful.
INFO:desk:Retaken control.


In [117]:
from panda_py import libfranka

panda = panda_py.Panda(hostname)
gripper = libfranka.Gripper(hostname)

INFO:panda:Connected to robot (192.168.1.11).
INFO:panda:Panda class destructor invoked (192.168.1.11).
INFO:panda:Stopping active controller (JointTrajectory).


In [118]:
# moq 2.93022 is beyond the joint wall: [-2.8973, 2.8973]tion generation in joint space

panda.move_to_start()

# call to get_pose produces a 4*4 matrix 
# representing the homogeneous transform from robot base to end-effector

pose = panda.get_pose()

# pose[2,3] -= .1 # The indices refer to third row and fourth column respectively, i.e. the z-coordinate.

# # The position in z is lowered by 0.1m
# # and passed to the inverse kinematics function to produce joint positions. 
# q = panda_py.ik(pose)
# # Finally the call to move_to_joint_position generates a motion from the current to the desired joint potions.
# panda.move_to_joint_position(q)

# print("Solved IK", q)

INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.08 seconds.
INFO:panda:Starting new controller (JointTrajectory).


In [119]:
panda.move_to_start()
pose = panda.get_pose()

q = panda_py.ik(pose)
# Finally the call to move_to_joint_position generates a motion from the current to the desired joint potions.
panda.move_to_joint_position(q)

print("Solved start pose IK", q)

INFO:panda:Stopping active controller (JointTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.07 seconds.
INFO:panda:Starting new controller (JointTrajectory).
INFO:panda:Stopping active controller (JointTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.07 seconds.
INFO:panda:Starting new controller (JointTrajectory).


Solved start pose IK [-0.00408259 -0.78351519  0.00302372 -2.35496117  0.00286078  1.57165106
  0.78539816]


In [ ]:
import numpy as np

panda.move_to_start()

# Get the position and orientation as separate arrays
pos = np.array(panda.get_position())
ori = np.array(panda.get_orientation())

# Ensure that the orientation is a 4x1 array (quaternion or similar)
# The position is a 3x1 array (x, y, z)
print(f"Position: {pos}, Orientation: {ori}")


# Now call the IK solver with separate position and orientation arrays
q = panda_py.ik(pos, ori)
print("Solved start pose IK (Initial):", q)


# Move the robot to the joint configuration returned by IK solver
pos += [0.1 , 0 , 0.1]
ori += [0, 0, 0, 0.1]

q = panda_py.ik(pos, ori)
panda.move_to_joint_position(q)

print("Solved start pose IK (after move):", q)


INFO:panda:Stopping active controller (JointTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.06 seconds.
INFO:panda:Starting new controller (JointTrajectory).
INFO:panda:Stopping active controller (JointTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.07 seconds.
INFO:panda:Starting new controller (JointTrajectory).


Position: [3.07476465e-01 2.42093371e-04 4.87061548e-01], Orientation: [ 9.99999418e-01 -1.00134137e-03  2.41658652e-04 -3.20716618e-04]
Solved start pose IK: [-0.00399094 -0.78378403  0.00280875 -2.35491378  0.00262479  1.5716144
  0.78539816]


In [102]:
# motion generation in Cartesian space

panda.move_to_start()

pos = panda.get_position()
ori = panda.get_orientation()

# pos = panda.get_position() 
print(f"initial_pose: {pos}, {ori}")
pos += [0.0 , 0 , -0.1]


# # resulting pose is passed directly to move_to_pose to produce a motion in Cartesian space.
panda.move_to_pose(positions=[pos], orientations=[ori])
# ori = panda.get_orientation()

pos = panda.get_position()
ori = panda.get_orientation()

# pos = panda.get_position() 
print(f"aftermove: {pos}, {ori}")
# pos = panda.get_position() 
# print(f"aftermove_pose: {pos}, {ori}")

ori += [3.14/4.0, 0, 0, 0]

# resulting pose is passed directly to move_to_pose to produce a motion in Cartesian space.
panda.move_to_pose(positions=[pos], orientations=[ori])
ori = panda.get_orientation()
pos = panda.get_position() 
print(f"aftermove_pose: {pos}, {ori}")



INFO:panda:Stopping active controller (CartesianTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.60 seconds.
INFO:panda:Starting new controller (JointTrajectory).
INFO:panda:Stopping active controller (JointTrajectory).
INFO:panda:Initializing motion generation (moveToPose).
INFO:motion:Computed Cartesian trajectory: 1 waypoint, duration 0.42 seconds.
INFO:panda:Starting new controller (CartesianTrajectory).


initial_pose: [0.30806945 0.00108481 0.48721348], [ 9.99992206e-01 -3.55724640e-03  1.46592524e-03 -8.86204473e-04]


INFO:panda:Stopping active controller (CartesianTrajectory).
INFO:panda:Initializing motion generation (moveToPose).
INFO:motion:Computed Cartesian trajectory: 1 waypoint, duration 0.18 seconds.
INFO:panda:Starting new controller (CartesianTrajectory).


aftermove: [0.31254503 0.00113544 0.39332044], [ 9.98876367e-01 -3.69724314e-03 -4.72419864e-02 -7.26735440e-04]
aftermove_pose: [0.31341838 0.00115412 0.3941126 ], [ 9.98967161e-01 -3.67658090e-03 -4.52831679e-02 -7.26982129e-04]


In [103]:
panda.move_to_start()

INFO:panda:Stopping active controller (CartesianTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.60 seconds.
INFO:panda:Starting new controller (JointTrajectory).


True

In [108]:
pos = panda.get_position()
ori = panda.get_orientation()

# pos = panda.get_position() 
print(f"initial_pose: {pos}, {ori}")

pos += [0.0 , 0 , -0.1]

q = panda_py.ik(positions=[pos], orientations=[ori])

# # resulting pose is passed directly to move_to_pose to produce a motion in Cartesian space.
panda.move_to_joint_position(q)



initial_pose: [0.30802878 0.001055   0.48718262], [ 9.99992877e-01 -3.40536710e-03  1.37714228e-03 -8.67456704e-04]


TypeError: ik(): incompatible function arguments. The following argument types are supported:
    1. (O_T_EE: numpy.ndarray[numpy.float64[4, 4]], q_init: numpy.ndarray[numpy.float64[7, 1]] = array([ 0. , -0.78539816, 0. , -2.35619449, 0. , 1.57079633, 0.78539816]), q_7: float = 0.7853981633974483) -> numpy.ndarray[numpy.float64[7, 1]]
    2. (position: numpy.ndarray[numpy.float64[3, 1]], orientation: numpy.ndarray[numpy.float64[4, 1]], q_init: numpy.ndarray[numpy.float64[7, 1]] = array([ 0. , -0.78539816, 0. , -2.35619449, 0. , 1.57079633, 0.78539816]), q_7: float = 0.7853981633974483) -> numpy.ndarray[numpy.float64[7, 1]]

Invoked with: kwargs: positions=[array([0.30802878, 0.001055  , 0.38718262])], orientations=[array([ 9.99992877e-01, -3.40536710e-03,  1.37714228e-03, -8.67456704e-04])]

In [ ]:
gripper.grasp(0, 0.1, 10, 0.4, 0.04)
#1st arg: 0 close gripper, >0 -> open 



True

In [50]:
gripper.move(0, 0.2)

# position and speed

True

In [ ]:
print("Position: ", panda.get_position())
print("Orientation: ", panda.get_orientation())

# print("Pose: ", panda.get_pose())



Position:  [ 0.30738739 -0.00056706  0.38513597]
Orientation:  [ 0.99995338 -0.00834506 -0.00362407  0.00323329]
Pose:  [[ 9.99834435e-01 -1.66659070e-02 -7.30176382e-03  3.07387388e-01]
 [-1.67127777e-02 -9.99839794e-01 -6.40580183e-03 -5.67061413e-04]
 [-7.19383554e-03  6.52677401e-03 -9.99952824e-01  3.85135973e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [52]:
pose = panda.get_pose()
print("pose: ", pose)
q = panda_py.ik(pose)

print("Solved IK", q)

panda.move_to_joint_position(q) 


INFO:panda:Stopping active controller (JointTrajectory).
INFO:panda:Initializing motion generation (moveToJointPosition).
INFO:motion:Computed joint trajectory: 1 waypoint, duration 0.15 seconds.
INFO:panda:Starting new controller (JointTrajectory).


pose:  [[ 9.99884498e-01 -1.39686854e-02 -5.98593695e-03  3.07315772e-01]
 [-1.39928319e-02 -9.99894033e-01 -4.01115552e-03 -3.91354215e-04]
 [-5.92927206e-03  4.09445243e-03 -9.99974039e-01  3.85538719e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Solved IK [-0.02594125 -0.80998017  0.02159639 -2.62837596  0.01191016  1.81255409
  0.78539816]


True

In [31]:
print(panda.get_state())
print(panda.get_model())


{"O_T_EE": [0.998186,-0.00329882,-0.0601197,0,-0.00337953,-0.999994,-0.00124089,0,-0.0601153,0.00144182,-0.99819,0,0.312286,3.5474e-05,0.440711,1], "O_T_EE_d": [0.999995,-0.0029257,-0.000691016,0,-0.00292654,-0.999995,-0.00122429,0,-0.000687431,0.0012263,-0.999999,0,0.307662,0.000108499,0.486512,1], "F_T_NE": [0.707107,-0.707107,0,0,0.707107,0.707107,0,0,0,0,1,0,0,0,0.1034,1], "NE_T_EE": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1], "F_T_EE": [0.707107,-0.707107,0,0,0.707107,0.707107,0,0,0,0,1,0,0,0,0.1034,1], "EE_T_K": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1], "m_ee": 0.73, "F_x_Cee": [-0.01,0,0.03], "I_ee": [0.001,0,0,0,0.0025,0,0,0,0.0017], "m_load": 0, "F_x_Cload": [0,0,0], "I_load": [0,0,0,0,0,0,0,0,0], "m_total": 0.73, "F_x_Ctotal": [-0.01,0,0.03], "I_total": [0.001,0,0,0,0.0025,0,0,0,0.0017], "elbow": [0.000344635,-1], "elbow_d": [0.000348337,-1], "elbow_c": [0,0], "delbow_c": [0,0], "ddelbow_c": [0,0], "tau_J": [0.279393,-6.22863,-0.747078,22.8987,0.757526,2.06341,-0.0321755], "tau_J_d": [-0.029